services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP port for RabbitMQ
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  producer:
    build:
      context: . # Build from the root of the workspace
      dockerfile: producer/Dockerfile
    container_name: producer
    ports:
      - "3000:3000" # Expose Rust app on port 3000
    volumes:
      - .:/usr/src/app # Mount the current directory to the container
    depends_on:
      - rabbitmq # Ensure RabbitMQ starts before the Rust app
    environment:
      RABBITMQ_ADDR: amqp://guest:guest@rabbitmq:5672 # Optional: Set RabbitMQ connection string for future use

  consumer:
    build:
      context: . # Build from the root of the workspace
      dockerfile: consumer/Dockerfile
    container_name: consumer
    depends_on:
      - producer
    environment:
      RABBITMQ_ADDR: amqp://guest:guest@rabbitmq:5672
    volumes:
      - .:/usr/src/app # Mount the current directory to the container

volumes:
  rabbitmq_data: # Named volume for persisting RabbitMQ data
